// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfpky0rfiMje-egeuBkIA5g3H4LgGzMs',
    appId: '1:425658436898:web:4b641546479911331ca97b',
    messagingSenderId: '425658436898',
    projectId: 'expense-tracker-x-debcd',
    authDomain: 'expense-tracker-x-debcd.firebaseapp.com',
    storageBucket: 'expense-tracker-x-debcd.firebasestorage.app',
    measurementId: 'G-HFEPTXG8Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrgQyK07l7dpPsSaICkNuOnXQ2CPD-lZY',
    appId: '1:425658436898:android:c6256ee87cf6ca551ca97b',
    messagingSenderId: '425658436898',
    projectId: 'expense-tracker-x-debcd',
    storageBucket: 'expense-tracker-x-debcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIZ7FX5Yy7gwbuht0lxLpAg5nm4dbWCE',
    appId: '1:425658436898:ios:79390992c3c69d4f1ca97b',
    messagingSenderId: '425658436898',
    projectId: 'expense-tracker-x-debcd',
    storageBucket: 'expense-tracker-x-debcd.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIZ7FX5Yy7gwbuht0lxLpAg5nm4dbWCE',
    appId: '1:425658436898:ios:79390992c3c69d4f1ca97b',
    messagingSenderId: '425658436898',
    projectId: 'expense-tracker-x-debcd',
    storageBucket: 'expense-tracker-x-debcd.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwfpky0rfiMje-egeuBkIA5g3H4LgGzMs',
    appId: '1:425658436898:web:deba2fdb54d8dcf01ca97b',
    messagingSenderId: '425658436898',
    projectId: 'expense-tracker-x-debcd',
    authDomain: 'expense-tracker-x-debcd.firebaseapp.com',
    storageBucket: 'expense-tracker-x-debcd.firebasestorage.app',
    measurementId: 'G-SK4SB3NHM9',
  );
}
